### Imports

In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

### Data Preprocessing

In [2]:
data_url = "./Data/card_transdata.csv"

data = pd.read_csv(data_url)

print(data.shape)

data.head()

(1000000, 8)


distance_from_home  distance_from_last_transaction  \
0           57.877857                        0.311140   
1           10.829943                        0.175592   
2            5.091079                        0.805153   
3            2.247564                        5.600044   
4           44.190936                        0.566486   

   ratio_to_median_purchase_price  repeat_retailer  used_chip  \
0                        1.945940              1.0        1.0   
1                        1.294219              1.0        0.0   
2                        0.427715              1.0        0.0   
3                        0.362663              1.0        1.0   
4                        2.222767              1.0        1.0   

   used_pin_number  online_order  fraud  
0              0.0           0.0    0.0  
1              0.0           0.0    0.0  
2              0.0           1.0    0.0  
3              0.0           1.0    0.0  
4              0.0           1.0    0.0

### Data Splitting

In [3]:
train_url = "./Data/Train/train_data.csv"
test_url = "./Data/Test/test_data.csv"

train_data = pd.read_csv(train_url)
test_data = pd.read_csv(test_url)

train_X = train_data.drop(columns="fraud")
train_Y = train_data["fraud"]

test_X = test_data.drop(columns="fraud")
test_Y = test_data["fraud"]

In [4]:
print(train_X.shape, train_Y.shape)
print(test_X.shape, test_Y.shape)

(800000, 7) (800000,)
(200000, 7) (200000,)


### KNN

#### Default - 5 Neighbors

In [24]:
ccdata_knn = KNeighborsClassifier(weights="distance")
ccdata_knn.fit(train_X, train_Y)

KNeighborsClassifier(weights='distance')

In [25]:
predict_Y_knn = ccdata_knn.predict(test_X)
acc_knn = accuracy_score(test_Y, predict_Y_knn)
print(acc_knn)

0.984885


In [28]:
confusion_matrix(test_Y, predict_Y_knn)

array([[180571,   1845],
       [  1178,  16406]], dtype=int64)

#### 1 Neighbor

In [29]:
ccdata_knn = KNeighborsClassifier(weights="distance", n_neighbors=1)
ccdata_knn.fit(train_X, train_Y)

KNeighborsClassifier(n_neighbors=1, weights='distance')

In [30]:
predict_Y_knn = ccdata_knn.predict(test_X)
acc_knn = accuracy_score(test_Y, predict_Y_knn)
print(acc_knn)

0.986235


In [31]:
confusion_matrix(test_Y, predict_Y_knn)

array([[180774,   1642],
       [  1111,  16473]], dtype=int64)

#### 2 Neighbors

In [32]:
ccdata_knn = KNeighborsClassifier(weights="distance", n_neighbors=2)
ccdata_knn.fit(train_X, train_Y)

KNeighborsClassifier(n_neighbors=2, weights='distance')

In [33]:
predict_Y_knn = ccdata_knn.predict(test_X)
acc_knn = accuracy_score(test_Y, predict_Y_knn)
print(acc_knn)

0.986235


In [34]:
confusion_matrix(test_Y, predict_Y_knn)

array([[180774,   1642],
       [  1111,  16473]], dtype=int64)

#### 3 Neighbors

In [35]:
ccdata_knn = KNeighborsClassifier(weights="distance", n_neighbors=3)
ccdata_knn.fit(train_X, train_Y)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [36]:
predict_Y_knn = ccdata_knn.predict(test_X)
acc_knn = accuracy_score(test_Y, predict_Y_knn)
print(acc_knn)

0.985315


In [37]:
confusion_matrix(test_Y, predict_Y_knn)

array([[180640,   1776],
       [  1161,  16423]], dtype=int64)

#### 10 Neighbors

In [38]:
ccdata_knn = KNeighborsClassifier(weights="distance", n_neighbors=10)
ccdata_knn.fit(train_X, train_Y)

KNeighborsClassifier(n_neighbors=10, weights='distance')

In [39]:
predict_Y_knn = ccdata_knn.predict(test_X)
acc_knn = accuracy_score(test_Y, predict_Y_knn)
print(acc_knn)

0.984375


In [40]:
confusion_matrix(test_Y, predict_Y_knn)

array([[180542,   1874],
       [  1251,  16333]], dtype=int64)